# Generated by Django 6.0.5 on 2026-06-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_submitted', 'Pago recibido'), ('payment_verified', 'Pago verificado'), ('payment_rejected', 'Pago rechazado'), ('plan_expiring', 'Plan próximo a vencer'), ('plan_expired', 'Plan vencido'), ('plan_renewed', 'Plan renovado'), ('competition_invite', 'Invitación a competencia'), ('competition_assigned', 'Competencia asignada'), ('progress_updated', 'Progreso actualizado'), ('athlete_assigned', 'Atleta asignado'), ('competition_reminder', 'Recordatorio de competencia')], max_length=30),
        ),
    ]
