# Generated by Django 6.0.5 on 2026-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('staff', 'Staff'), ('athlete', 'Athlete')], default='coach', max_length=10),
        ),
    ]
