# Generated by Django 6.0.5 on 2026-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(choices=[('figure_skating', 'Figure Skating'), ('speed', 'Speed'), ('power', 'Power')], max_length=20)),
                ('status', models.CharField(choices=[('on_ice', 'On Ice'), ('in_facility', 'In Facility'), ('off_duty', 'Off Duty')], default='off_duty', max_length=15)),
                ('athletes_count', models.PositiveIntegerField(default=0)),
                ('next_session_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
