# Generated by Django 6.0.5 on 2026-05-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='specialty',
            field=models.CharField(choices=[('speed', 'Speed'), ('power', 'Power'), ('figure_skating', 'Figure Skating')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('in_facility', 'In Facility'), ('off_duty', 'Off Duty'), ('on_ice', 'On Ice')], default='off_duty', max_length=15),
        ),
    ]
