# Generated by Django 6.0.5 on 2026-06-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_score', models.PositiveIntegerField(default=0)),
                ('technique_score', models.PositiveIntegerField(default=0)),
                ('form_score', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='athletes.athlete')),
            ],
            options={
                'verbose_name_plural': 'Athlete progress',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
