# Generated by Django 6.0.5 on 2026-06-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athleteprogress'),
        ('competitions', '0001_initial'),
        ('staff', '0003_alter_staffmember_specialty_alter_staffmember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invitado'), ('confirmed', 'Confirmado'), ('participated', 'Participó')], default='invited', max_length=15)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_assignments', to='athletes.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_athletes', to='competitions.competition')),
            ],
            options={
                'verbose_name_plural': 'Competition athletes',
                'unique_together': {('competition', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coaches', to='competitions.competition')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_assignments', to='staff.staffmember')),
            ],
            options={
                'verbose_name_plural': 'Competition coaches',
                'unique_together': {('competition', 'staff_member')},
            },
        ),
    ]
