# Generated by Django 6.0.5 on 2026-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competitionathlete_competitioncoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionathlete',
            name='status',
            field=models.CharField(choices=[('invited', 'Invitado'), ('confirmed', 'Confirmado'), ('participated', 'Participó'), ('declined', 'Declinado')], default='invited', max_length=15),
        ),
    ]
