import {
  HomeIcon,
  CreditCardIcon,
  UserGroupIcon,
  TrophyIcon,
  IdentificationIcon,
  ArrowRightOnRectangleIcon,
  BellIcon,
  QuestionMarkCircleIcon,
  UserIcon,
  PlusIcon,
  CalendarIcon,
  ChevronRightIcon,
  ArrowDownTrayIcon,
  ClockIcon,
  BoltIcon,
  SparklesIcon,
  ChartBarIcon,
  ExclamationTriangleIcon,
  WalletIcon,
  CalendarDaysIcon,
  MapPinIcon,
  CheckCircleIcon,
  UserPlusIcon,
  ArrowTrendingUpIcon,
  EyeIcon,
  Bars3Icon,
  MagnifyingGlassIcon,
  Cog6ToothIcon,
  StarIcon,
  ShieldCheckIcon,
  DocumentTextIcon,
  ArrowLeftIcon,
  EnvelopeIcon,
  EyeSlashIcon,
  LinkIcon,
  XMarkIcon,
  UserMinusIcon,
} from '@heroicons/react/24/outline';
import {
  HomeIcon as HomeIconSolid,
  CreditCardIcon as CreditCardIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  TrophyIcon as TrophyIconSolid,
  IdentificationIcon as IdentificationIconSolid,
  BellIcon as BellIconSolid,
  StarIcon as StarIconSolid,
} from '@heroicons/react/24/solid';

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  home: HomeIcon,
  home_solid: HomeIconSolid,
  payments: CreditCardIcon,
  payments_solid: CreditCardIconSolid,
  group: UserGroupIcon,
  group_solid: UserGroupIconSolid,
  emoji_events: TrophyIcon,
  emoji_events_solid: TrophyIconSolid,
  badge: IdentificationIcon,
  badge_solid: IdentificationIconSolid,
  logout: ArrowRightOnRectangleIcon,
  notifications: BellIcon,
  notifications_solid: BellIconSolid,
  help: QuestionMarkCircleIcon,
  person: UserIcon,
  add: PlusIcon,
  event: CalendarIcon,
  event_available: CalendarDaysIcon,
  download: ArrowDownTrayIcon,
  chevron_right: ChevronRightIcon,
  speed: BoltIcon,
  directions_run: SparklesIcon,
  account_balance_wallet: WalletIcon,
  calendar_month: CalendarDaysIcon,
  schedule: ClockIcon,
  warning: ExclamationTriangleIcon,
  pending_actions: ClockIcon,
  location_on: MapPinIcon,
  arrow_forward: ArrowRightOnRectangleIcon,
  leaderboard: ChartBarIcon,
  bar_chart: ChartBarIcon,
  person_add: UserPlusIcon,
  trending_up: ArrowTrendingUpIcon,
  check_circle: CheckCircleIcon,
  verified_user: CheckCircleIcon,
  update: Cog6ToothIcon,
  search: MagnifyingGlassIcon,
  settings: Cog6ToothIcon,
  star: StarIcon,
  star_solid: StarIconSolid,
  shield: ShieldCheckIcon,
  security: ShieldCheckIcon,
  document: DocumentTextIcon,
  description: DocumentTextIcon,
  eye: EyeIcon,
  visibility: EyeIcon,
  visibility_off: EyeSlashIcon,
  menu: Bars3Icon,
  arrow_back: ArrowLeftIcon,
  email: EnvelopeIcon,
  link: LinkIcon,
  link_off: XMarkIcon,
  person_off: UserMinusIcon,
  cancel: XMarkIcon,
};

interface IconProps {
  name: string;
  className?: string;
  solid?: boolean;
}

export default function Icon({ name, className = 'w-6 h-6', solid = false }: IconProps) {
  const key = solid ? `${name}_solid` : name;
  const IconComponent = iconMap[key] || iconMap[name] || HomeIcon;
  return <IconComponent className={className} />;
}
