# Generated by Django 6.0.6 on 2026-06-15 21:02

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('J', 'Jurídica')], default='V', max_length=1)),
                ('id_number', models.CharField(max_length=20)),
                ('amount_ves', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('bank_origin', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to=apps.payments.models.comprobante_upload_path)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments.invoice')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
