# Generated by Django 6.0.5 on 2026-06-15 23:29

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('plan_renewal', 'Renovación de plan'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.payments.models.comprobante_upload_path),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='method',
            field=models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia'), ('cash', 'Efectivo')], max_length=20),
        ),
    ]
