# Generated by Django 6.0.6 on 2026-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_invoice_type_alter_paymentproof_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
